version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ../jenkins-app:/project
    networks:
      - jenkins-net
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
